[2024-03-29T17:27:53.899+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Teste.não_valido manual__2024-03-29T17:27:45.786392+00:00 [queued]>
[2024-03-29T17:27:53.907+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Teste.não_valido manual__2024-03-29T17:27:45.786392+00:00 [queued]>
[2024-03-29T17:27:53.908+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T17:27:53.942+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): não_valido> on 2024-03-29 17:27:45.786392+00:00
[2024-03-29T17:27:53.948+0000] {standard_task_runner.py:60} INFO - Started process 108 to run task
[2024-03-29T17:27:53.949+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_Teste', 'não_valido', 'manual__2024-03-29T17:27:45.786392+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_test.py', '--cfg-path', '/tmp/tmpz4g6s68f']
[2024-03-29T17:27:53.951+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask não_valido
[2024-03-29T17:27:53.982+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_Teste.não_valido manual__2024-03-29T17:27:45.786392+00:00 [running]> on host dedf4740d4fb
[2024-03-29T17:27:54.053+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_Teste' AIRFLOW_CTX_TASK_ID='não_valido' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T17:27:45.786392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T17:27:45.786392+00:00'
[2024-03-29T17:27:54.054+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T17:27:54.055+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Quantidade Inválida']
[2024-03-29T17:27:54.098+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T17:27:54.100+0000] {subprocess.py:93} INFO - Quantidade Inválida
[2024-03-29T17:27:54.100+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T17:27:54.118+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_Teste, task_id=não_valido, execution_date=20240329T172745, start_date=20240329T172753, end_date=20240329T172754
[2024-03-29T17:27:54.163+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T17:27:54.174+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
